services:
    chat:
      build: .
      ports:
      - "8080:8080"
      depends_on: 
        - db
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    db:
      image: postgres
      restart: always
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      # do I want this to be exposed?
      ports:
        - 5432:5432
	#remove later
    adminer:
      image: adminer
      restart: always
      ports:
        - 8181:8080
volumes:
  pgdata: