services:
    chat:
      build: .
      ports:
      - "8080:8080"
      depends_on: 
        - postgres
    
    postgres:
      image: postgres
      restart: always
      environment: 
        - POSTGRES_USER=pg
        - POSTGRES_PASSWORD=1234
      volumes:
        - pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
volumes:
  pgdata: